### ISSUE TITLE
Ledger support?

### ISSUE THREAD

**Issue by mobilekosmos** [ElrondNetwork/elrond-sdk-erdkotlin#12]
This lib doesn't support a hardware ledger like the js version, right?

**Comment by Alexandre-saddour** [comment]
Hello,
What do you want to accomplish exactly ?
What can you do with erdjs that you cannot do with this sdk ?

**Comment by mobilekosmos** [comment]
I want to add "login with elrond"  to native apps, like you have today "login with metamask" etc. 

Or if you want a more technical answer: port [this](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/src/MoralisErd.js) to kotlin.

**Comment by Alexandre-saddour** [comment]
Thanks for inputs.
Indeed, Erdkotlin does not support this feature at the moment.

There are other priorities for this SDK right now.
However, it's now on my todo list and I will definitely look at it in the future. 

In the meantime, PR are welcome.

**Comment by schimih** [comment]
I will close this issue as long as we do not offer support for kotlin at the moment.

Any PR from the community is more than welcome.
