### ISSUE TITLE
Support for abi deserialisation

### ISSUE THREAD

**Issue by corneloaie** [ElrondNetwork/elrond-sdk-erdkotlin#13]
As of now the erdjs libarary offers the possibility to use the abi json file as a way to serialise/deserialise the data to/from the blockchain. Sadly there is no such library open sourced that works for every abi format and for custom specific classes that the libraries offer ( e.g. Address). In terms of creating a unified ecosystem to display data from both web and mobile, an abi decoder that reproduces the outcome of the one used in erdjs is required.

**Comment by schimih** [comment]
I will close this issue as long as we do not offer support for kotlin at the moment.

Any PR from the community is more than welcome.
