### ISSUE TITLE
Intent to Maiar app for login and signing transaction

### ISSUE THREAD

**Issue by corneloaie** [ElrondNetwork/elrond-sdk-erdkotlin#14]
The library the way it is now can only create a Wallet instance based on the given mnemonics and sign transactions and so on. As a developer I want to offer the users the possibility to login with the library using the maiar app.
Basically the sdk needs to write intents for the Maiar app to authenticate and later sign transactions, and the maiar app has to have defined in the <intent-filters> such use cases used by the erdkotlin sdk.

**Comment by schimih** [comment]
I will close this issue as long as we do not offer support for kotlin at the moment.

Any PR from the community is more than welcome.
